// Copyright Fissure Entertainment, Pty Ltd. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "Engine/DataTable.h"
#include "InstancedStruct.h"
#include "ItemInstancer.generated.h"

class UItemInstancingContextFunction;
/**
 * An Object that provides a function for generating Item Instances from a Drop Table.
 */
UCLASS(ClassGroup = ("Generic Itemization"), BlueprintType, Blueprintable, EditInlineNew)
class GENERICITEMIZATION_API UItemInstancer : public UObject
{
	GENERATED_BODY()

public:

	UItemInstancer();

	/**
	 * Generates Item Instances from the DropTable.
	 * 
	 * @param UserContextData		Arbitrary data that you may want to pack with useful information to pass through during the Item Instancing Process and for access to other external systems.
	 * @param OutItemInstances		All of the ItemInstances that were generated from the DropTable.
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, BlueprintAuthorityOnly, Category = "Generic Itemization")
	bool GenerateItems(FInstancedStruct UserContextData, TArray<FInstancedStruct>& OutItemInstances);

protected:

	/* The DropTable we will use to make Item selections from. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta = (RowType = "/Script/GenericItemization.ItemDropTableCollectionEntry"), Category = "Generic Itemization")
	FDataTableRowHandle ItemDropTable;

	/* Class that manages generating the ItemInstancingContext for Items that are generated by this Instancer. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Generic Itemization")
	TSubclassOf<UItemInstancingContextFunction> ContextProviderFunction;
	
};
