// Copyright Fissure Entertainment, Pty Ltd. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Engine/DataTable.h"
#include "InstancedStruct.h"
#include "ItemDropperComponent.generated.h"

class AItemDrop;
class UItemInstancingContextFunction;

/**
 * A Component that sits on an Actor to facilitate the entrypoint to dropping Items for that Actor from a specified DropTable.
 */
UCLASS(ClassGroup = ("Generic Itemization"), meta = (BlueprintSpawnableComponent))
class GENERICITEMIZATION_API UItemDropperComponent : public UActorComponent
{
	GENERATED_BODY()

public:	

	UItemDropperComponent();

	/**
	 * Drops Items from this dropper according to the selected ItemDropTable. 
	 * 
	 * @param UserContextData		Arbitrary data that you may want to pack with useful information to pass through during the Item Instancing Process and for access to other external systems.
	 * @param ItemDrops				All of the ItemDrop Actors that were produced for ItemInstances that were generated from the DropTable.
	 * @param bDeferredSpawn		Whether or not to use deferred spawning on the ItemDrops or immediate. Deferred allows you to manipulate them (such as setting their Transforms) prior to final spawning, you must manually call UGameplayStatics::FinishSpawningActor.
	 */
	UFUNCTION(BlueprintNativeEvent)
	bool DropItems(const FInstancedStruct& UserContextData, TArray<AItemDrop*>& ItemDrops, bool bDeferredSpawn = false);

protected:

	/* The DropTable we will use to make Item selections from. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta = (RowType = "/Script/GenericItemization.ItemDropTableCollectionEntry"))
	FDataTableRowHandle ItemDropTable;

	/* The type of Item Drop Actor we will use to represent the Items we will drop within the world. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	TSubclassOf<AItemDrop> ItemDropClass;

	/* Class that manages generating the ItemInstancingContext for Items that are generated by this dropper. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	TSubclassOf<UItemInstancingContextFunction> ContextProviderFunction;

};
