// Copyright Fissure Entertainment, Pty Ltd. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace GenericItemizationGameplayTags
{
	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType);
	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(QualityType);
	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AffixType);
	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserData);
	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mutator);

	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemInstanceChange);
	GENERICITEMIZATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StackCountChange);
}